version: '3'

services:
    postgres:
        image: postgres:latest
        container_name: postgres
        hostname: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_HOST: ${DATABASE_URL}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
            POSTGRES_DB: my-pets-site
        volumes:
            - postgres-data:/var/lib/postgresql/data
        restart: unless-stopped
volumes:
    postgres-data:
