version: '3.9'

services:
    postgres:
        image: postgres:latest
        container_name: carematey
        hostname: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
            POSTGRES_DB: postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data
        restart: unless-stopped
volumes:
    postgres-data:
